import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import './globals.css';

const geistSans = Outfit({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

// const clashDisplay = clash

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
